[project]
name = "llm-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "colorama>=0.4.6",
    "ollama>=0.5.1",
    "openai>=1.0.0",
    "pydantic>=2.0.0",
    "requests>=2.32.3",
]
